-- CSIR-SERC Intranet Portal Schema

-- 1. Users (Local Admins)
-- Employees authenticate via Active Directory (LDAP), so this table is primarily for 
-- local administrators or content managers who need publishing rights.
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL, -- Store bcrypt hashes
    full_name VARCHAR(100),
    role VARCHAR(20) CHECK (role IN ('admin', 'editor')) DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Journal Posts (News & Updates)
CREATE TABLE journal_posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT,
    priority BOOLEAN DEFAULT FALSE, -- Pinned posts
    category VARCHAR(50) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Circulars (OMs & Official Docs)
CREATE TABLE circulars (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    summary TEXT,
    ref_number VARCHAR(100),
    issue_date DATE NOT NULL,
    is_archived BOOLEAN DEFAULT FALSE,
    category VARCHAR(50) NOT NULL,
    attachment_url TEXT, -- Path to file in storage (e.g., S3 or local upload dir)
    uploaded_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Quick Link Categories
CREATE TABLE link_categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER DEFAULT 0
);

-- 5. Quick Links
CREATE TABLE quick_links (
    id SERIAL PRIMARY KEY,
    category_id INTEGER REFERENCES link_categories(id) ON DELETE CASCADE,
    title VARCHAR(100) NOT NULL,
    url TEXT NOT NULL,
    is_external BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0
);

-- 6. Gallery Albums
CREATE TABLE gallery_albums (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    cover_image_url TEXT,
    event_date DATE,
    photo_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. Holidays
CREATE TABLE holidays (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    type VARCHAR(20) CHECK (type IN ('gazetted', 'restricted', 'optional', 'institution')),
    is_tentative BOOLEAN DEFAULT FALSE,
    notes TEXT,
    color_hex VARCHAR(7) DEFAULT '#ef4444'
);

-- Indexes for performance
CREATE INDEX idx_journal_published ON journal_posts(published_at DESC);
CREATE INDEX idx_circulars_issue_date ON circulars(issue_date DESC);
CREATE INDEX idx_circulars_archived ON circulars(is_archived);

-- Seed Default Admin User (Password: admin123)
-- Note: In production, use a proper bcrypt hash generated by your backend.
INSERT INTO users (username, password_hash, full_name, role)
VALUES ('admin', '$2b$10$EpOu....placeholderhash...', 'System Administrator', 'admin');
